-- =====================================================
-- EXTEND SUBSCRIPTION WITH ACCUMULATED DAYS (FIXED)
-- =====================================================
-- This function is superseded by database/25_fix_subscription_extension.sql
-- See that file for the corrected version that:
-- 1. EXTENDS active subscriptions from expires_at (never overwrites)
-- 2. UPDATES expired subscriptions instead of creating duplicates
-- 3. Only INSERTs when no subscription exists at all
--
-- Run database/25_fix_subscription_extension.sql to apply the fix.
