-- Per-user notification preferences
CREATE TABLE IF NOT EXISTS notification_settings (
  user_id CHAR(36) NOT NULL PRIMARY KEY,
  enable_all TINYINT(1) NOT NULL DEFAULT 1,
  morning TINYINT(1) NOT NULL DEFAULT 1,
  todo TINYINT(1) NOT NULL DEFAULT 1,
  pomodoro TINYINT(1) NOT NULL DEFAULT 1,
  motivational TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sample
INSERT IGNORE INTO notification_settings (user_id) VALUES ('00000000-0000-0000-0000-000000000001');