// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Support both Next.js (process.env.NEXT_PUBLIC_*) and Vite (import.meta.env.VITE_*)
const SUPABASE_URL =
  (process.env.NEXT_PUBLIC_SUPABASE_URL as string | undefined) ||
  (typeof import.meta !== 'undefined' ? (import.meta as any).env?.VITE_SUPABASE_URL as string | undefined : undefined);

const SUPABASE_PUBLISHABLE_KEY =
  (process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY as string | undefined) ||
  (typeof import.meta !== 'undefined' ? (import.meta as any).env?.VITE_SUPABASE_ANON_KEY as string | undefined : undefined);

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  // Fail fast in non-configured environments
  // eslint-disable-next-line no-console
  console.error('Missing Supabase environment variables. Set NEXT_PUBLIC_SUPABASE_URL/NEXT_PUBLIC_SUPABASE_ANON_KEY (Next.js) or VITE_SUPABASE_URL/VITE_SUPABASE_ANON_KEY (Vite).');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL || '', SUPABASE_PUBLISHABLE_KEY || '', {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});